#!/bin/bash
bspc monitor -d I II III IV V
bspc config focus_follows_pointer true
bspc config border_width 0
bspc config window_gap 0
bspc rule -a firefox state=fullscreen, desktop=II
bspc rule -a code-oss state=fullscreen, desktop=I
xsetroot -cursor_name left_ptr
bspc mousebind super + right mouse resize
read width height < <(xrandr | grep '*' | awk '{print $1}' | head -n 1 | sed 's/x/ /')
bspc rule -a Alacritty state=floating, rectangle=$((width / 2))x$((height / 3))+$(($width / 4))+$((height / 3))
