#!/bin/bash
bspc monitor -d I II III IV V
bspc config focus_follows_pointer true
bspc config border_width 0
bspc config window_gap 0
bspc rule -a firefox state=fullscreen, desktop=II
bspc rule -a code-oss state=fullscreen, desktop=I
bspc rule -a Alacritty state=floating, rectangle=800x400+560+340
bspc config drag_window_mod super
bspc config drag_window_center true
xsetroot -cursor_name left_ptr
