#!/bin/bash
bspc monitor -d I II III IV V
bspc config focus_follows_pointer true
bspc config border_width 0
bspc config window_gap 0
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config normalize_border_on_focus false
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc mousebind super + right mouse resize
xset -dpms
xset s off
gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
read width height < <(xrandr | grep '*' | awk '{print $1}' | head -n 1 | sed 's/x/ /')
bspc rule -a Alacritty state=floating, rectangle=$((width / 2))x$((height / 3))+$(($width / 4))+$((height / 3))
